### ISSUE TITLE
Canvas unsafe code in the wild

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/unsafe-code-guidelines#146]
I think we should organize a kind of "canvas" to find examples of how unsafe code is used in the wild. To start, it'd be great to enumerate a list of interesting places to look. 

Here is my start at a list. Further nominations welcome. I'll try to keep the list up to date. Moreover, if you feel you've examined the source, open any relate issues and we can check it off.
- Standard library:
  - [ ] [btree](https://github.com/rust-lang/rust/tree/master/src/libcollections/btree), esp. the iterators
  - [ ] [hashmap](https://github.com/rust-lang/rust/tree/master/src/libstd/collections/hash)
  - [ ] ...?
- External libraries:
  - [ ] [`rayon`](https://github.com/nikomatsakis/rayon/)
  - [ ] [`take_mut`](https://crates.io/crates/take_mut)
  - [ ] [`abomonation`](http://www.frankmcsherry.org/serialization/2015/05/04/unsafe-at-any-speed.html)
  - [ ] [`ndarray`](https://github.com/bluss/rust-ndarray/)
  - [ ] [`intrusive_collections`](https://github.com/Amanieu/intrusive-rs/blob/master/src/lib.rs#L267) by @Amanieu, cited in #19
  - [ ] [`rental`](https://docs.rs/rental/0.3.3/rental/)

Other thoughts for packages? Is this a fruitful thing to examine?

**Comment by Shnatsel** [comment]
I'm not sure what this issue is supposed to achieve that downloading and grepping crates.io or searching for "unsafe" in Rust code on Github would not.

But here are some bugs in unsafe code found in the wild, w/ short analysis. More of them here: https://rustsec.org/advisories/

Interesting or Rust-specific bugs:

1. https://github.com/servo/rust-smallvec/issues/101 - double free if iterator over non-Copy type panics. Fixed via "set length on drop" trick.
1. `inflate` crate: unsafe code due to missing safe abstraction (no way to append contents of vector to itself), I've opened [an RFC](https://github.com/rust-lang/rfcs/pull/2714) to provide one. Vulnerable, simplified example [here](https://github.com/rust-lang/rfcs/pull/2714#issuecomment-504671231).
1. https://github.com/ruuda/claxon/issues/10 exposure of uninitialized memory because of missing abstraction for an output buffer. The missing abstraction [actually exists as a crate](https://crates.io/crates/buffer) but nobody uses it because getting rid of 1-2 unsafe blocks per crate doesn't seem to be worth adding another dependency with unsafe code in it. In this case could be patched without regressing performance by requesting zeroed memory from the OS. This vuln triggered [documentation improvements](https://github.com/rust-lang/rust/issues/54628). I had to write a [custom tool](https://github.com/Shnatsel/libdiffuzz) to find this bug!

Boring but serious bugs:

1. [CVE in str::repeat](https://github.com/rust-lang/rust/pull/54397), also victim of appending vector to itself unsafely, didn't check for overflow in capacity calculation.
1. https://github.com/servo/rust-smallvec/issues/148 - use-after-free due to logic bug, boring all the way
1. https://github.com/Frommi/miniz_oxide/pull/47 - out-of-bounds write due to missing check. Now that `u64::to_le_bytes` is stabilized the `unsafe` is no longer needed. There is also [precedent for the reverse pattern](https://github.com/Frommi/miniz_oxide/pull/48) with `from_le_bytes` and `TryInto`. Safe versions are exactly as fast as the unsafe ones.

**Comment by JakobDegen** [comment]
Discussed in backlog bonanza: Not so sure this issue is providing much value and the discussion here is quite old. Closing
