### ISSUE TITLE
Use "C-compatible layout" subsections consistently

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/unsafe-code-guidelines#184]
We currently mix sub-sections called `repr(C)` and "C-compatible layout" and probably other terms. We should make this consistent.

**Comment by RalfJung** [comment]
I think the title should include `repr(C)` (not "repr C"). Whether it also says "C-compatible" I have no opinion on.

**Comment by Lokathor** [comment]
`repr(C)` should absolutely be used as the primary term because it's the language's term.

When talking in Discord and such I sometimes write "reprC" as shorthand, particularly on a phone where symbols are harder to muck with, but I've never needed to write "C-compatible layout" myself. It seems a lot more wordy.

**Comment by JakobDegen** [comment]
Closing, since we're not tracking the work in the repo anymore
