### ISSUE TITLE
Thread cancellation, asynchronous unwinding exceptions and their interaction with drops

### ISSUE THREAD

**Issue by nagisa** [rust-lang/unsafe-code-guidelines#211]
So during the all-hands we identified a use-case that would be good to be documented in the unsafe code guidelines.

There are at least three sources of "cancellation" which might end up "removing" (in Taylor’s words) a value without "dropping" it, which in turn results in unsoundness for e.g. rayon, crossbeam, &pin stuff. These sources are:

1. `longjmp`/`setjmp` (used in practice for error handling by rust lua and perhaps many other embedded languages/interpreters);
2. `pthread_cancel`: which can run either an asynchronous unwinding exception (might occur at any program point) or raise an unwindingexception at well specified points such as `sleep`; exact behaviour is specified by `pthread_setcancelstate`.
3. `pthread_exit`, `pthread_kill`: which will "stop" the thread, potentially executing some arbitrary code and cleaning the thread up (freeing thread’s stack).

There’s no question that these functions may be useful in one scenario or the other, so it would be good if we figured out scenarios in which these functions are sound to use (e.g. if the thread stack contains only `Copy` types) and encoded this information into our unsafe code guidelines book.

cc @nikomatsakis @cramertj

**Comment by comex** [comment]
What happens with `-C panic=abort`?

**Comment by RalfJung** [comment]
I don't think any of the examples in the OP are affected by that?

**Comment by gnzlbg** [comment]
@comex

> What happens with -C panic=abort?

I haven't tried, but IIUC on Itanium-C++ ABI thread cancelation uses `Unwind_ForceUnwind` which means that the stack frames would be unwound even if `-C panic=abort` (whether that does consistently run destructors or not, I don't know). 

On windows, where a `longjmp` is implemented using exceptions does unwind frames even when `-C panic=abort`, @kyren tested this for rlua, which works, but rlua does not have types with destructors in the frames that get unwound. @kyren added types with destructors to it, and if the type is in the same frame that calls an `extern "C"` function that unwinds, currently, its destructor is not run, but if it is in a different frame, then its destructor is run. This might have to do with how we currently implement things in Rust, and does not necessary match what C++ does (e.g. maybe this is a current implementation bug, our current tests for this are here (https://github.com/rust-lang/rust/tree/master/src/test/run-make-fulldeps/longjmp-across-rust) and they do not test that the destructor is actually run. The destructors there do nothing, e.g., as opposed to trying to count how many times they are invoked.  

Notice that when `-C panic=abort` we stamp `nounwind` everywhere, but LLVM says that it is ok for `nounwind` functions to unwind in certain specific ways.

**Comment by RalfJung** [comment]
Also see https://github.com/rust-lang-nursery/reference/pull/693#issuecomment-542677490 for an approximate model of stack frame and their dropping by @gnzlbg.

**Comment by comex** [comment]
I checked:

On Darwin, `pthread_cancel` doesn't use unwinding at all; it uses a separate linked list to track pthread_cleanup handlers.  As such, it will never run Rust destructors.

On Linux/glibc, `pthread_cancel` does indeed use `_Unwind_ForcedUnwind`.

On both OSes, `pthread_exit` **uses the same code path** as `pthread_cancel`, so the behavior is equivalent (unwinding on Linux, not on Darwin).

Here are some test results with both panic=unwind and panic=abort on Linux and macOS – various types of exotic crashes:

https://gist.github.com/comex/401f5c02f066fdea8e06c75a28267247

**Comment by gnzlbg** [comment]
@comex thanks!

> On Darwin, pthread_cancel doesn't use unwinding at all; it uses a separate linked list to track pthread_cleanup handlers. As such, it will never run Rust destructors.

This is interesting, because it doesn't work exactly like a longjmp since it runs some `pthread_cleanup` handlers :D 

I tried to visualize all the info and came up with this table:

| name | kind | runs destructors? | stoppable? | pausable? | aborts on aborts-on-panic-shims|
|-------|--------|--------|---------|--------|------|
| Rust panic | native | yes | catch | catch+resume |  yes |
| C++ throw | foreign | yes | catch could | catch+resume could  | yes | 
| pthread_cancel (linux) | foreign | yes | no | catch+resume could | no | 
| pthread_cancel (osx) | foreign | no | ? | ? | no |
| longjmp (linux) | foreign | no | no (setjmp only) | no | no |
| longjmp (windows-SEH) | foreign | yes | catch could| catch+resume could | no |

Instead of specifying the behavior of each of these on each platform, it might be better to specify the behavior of Rust depending on the columns. 

* If the kind is native, the behavior is well-defined and does ...
* If the kind is foreign, the behavior might be undefined, depending on other factors
* If the unwind does not run destructors, the behavior is undefined if unwinding deallocates drop types with safety invariants that require running destructors like `Pin`
* If the unwind is not stoppable or pausable, the behavior is undefined if the unwind reaches a thread boundary
* If the unwind does not abort on abort-on-panic shims and runs destructors and there are types with destructors in the frames, the behavior is undefined (e.g. calling a `nounwind` function that ends up unwinding such that destructors run might lead to only some destructors being run, depending on optimizations) 
* Some guarantees for `catch_unwind`, for example:
   * if the unwind is foreign, the behavior is UB
   * or, if the unwind is foreign, catch unwind never catches the unwind 

So if you have a platform and want to call some function that panics, you'd just fill in a row in the table, and answer the questions to see when the behavior is defined, and to what.

Something like that might end up reducing the amount of UB to few special cases, e.g.:

* deallocating a Pin without calling its destructor
* unwinding through a thread boundary with an unwind that cannot be stopped or paused (e.g. a longjmp that's not caught by its setjmp on the current thread)
* unwind is not caught by abort-on-panic-shims but runs destructors and there are types with drop glue on frames (e.g. longjmp on windows-seh if the frames have types with destructors)

leaving a lot of useful cases as "well-defined".

**Comment by JakobDegen** [comment]
Closing in favor of #404 which is more specific than this one
