### ISSUE TITLE
unsafe feature

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/unsafe-code-guidelines#238]
In a third party library crate there can be unsafe blocks.
Is it possible to wrap an unsafe block inside a feature?
So the calling crate can allow or forbid the use of the unsafe feature and consequently the unsafe block.
Sometimes the crate library can provide a safe code alternative, but with slower performances.
If the feature is mandatory, than it is easy to find what code needs to be scrutinized.
Something like this:
```rust
unsafe("unsafe_feature_to_read_file_x"){
                let path = "x";
                file_content = FFI C code::read_file(path);
            }
```

**Comment by RalfJung** [comment]
Welcome, and thanks for the suggestion! I do not understand what you are concretely proposing/asking, but the syntax you are using is not currently possible. If you want to discuss this as a possible extension to the language, I think https://internals.rust-lang.org/ is the right place. Eventually, this would then become an RFC. I suggest you also expand your description a lot, because I don't understand if by "feature" you mean "cargo feature" or nightly `#[feature]` flag or something else, nor do I understand what the exact meaning if your new syntax is.

But either way I'm afraid this repository is, I think, not the right place for such pre-RFC discussions.
