### ISSUE TITLE
Constructing ZSTs from thin air

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/unsafe-code-guidelines#250]
Am I correct in thinking that the following function safe and sound?
```rust
fn test<F: Fn(&str) + Copy>(f: F) {
    assert_eq!(mem::size_of::<F>(), 0);
    let y: F = unsafe { mem::zeroed() };
    y("example");
}
```

My reasoning is:
1) `F` must be safely constructible because it's `Copy` and we have `f` which we *could* have copied.
2) We assert the F is a ZST and we already know F is inhabited, so `mem::zeroed()` must be well defined.

In the real code the "example f" is not available at the point where I want to construct a new F, but I still know that it previously existed due to module-level constraints.

**Comment by digama0** [comment]
If it was a `PhantomData<&'a T>`, this would allow you to violate the lifetime of the original reference (perhaps not with the code as given but certainly if you know only that "it previously existed"). More generally, this seems problematic for ZSTs that carry some semantic information (like an unsafe invariant) that is particular to the crate that owns the type.

**Comment by Diggsey** [comment]
I added `Send + 'static` bounds to F as well, I think that should cover any possible semantic information. With those two bounds I could emulate the behaviour by storing `F` into a global variable and then retrieving it from within `test`.

**Comment by digama0** [comment]
I think in that case you are covered from Miri's point of view, if you can actually write the code that would do this (by storing F in a global ZST variable and copying it out), since as far as memory access is concerned it should lower to the same sequence of operations (since all the ZST operations are no-ops).

You could even do that dance, keeping a static `Option<F>`, which would not be zero overhead but would force you to update the flag when you receive the token. You could also use `MaybeUninit<F>` for this to make it zero overhead, where the unsafety comes from the lack of a data dependency from the value that you capture and the copy that you make later. This is easier to certify as UB-free, since it is simply a zero-sized instantiation of perfectly normal operations, although it is a lot of hoopla for a ZST.

**Comment by RalfJung** [comment]
> I added Send + 'static bounds to F as well, I think that should cover any possible semantic information. With those two bounds I could emulate the behaviour by storing F into a global variable and then retrieving it from within test.

Yeah, that seems like a sufficient condition to me. It is also okay to "multiply" ZST `Copy` types, i.e., given a `&[T]` with such a `T` it is okay to double the length of the slice; that covers the case where you do this out-of-thin-air construction several times.

**Comment by Diggsey** [comment]
Thanks 👍
