### ISSUE TITLE
Faking `Ordering::Consume`

### ISSUE THREAD

**Issue by thomcc** [rust-lang/unsafe-code-guidelines#264]
`load(Consume)` is cursed and probably never will exist. LLVM doesn't support it, and there aren't really any correct implementations of it, and it probably is a broken part of the C++ memory model... It IIUC was added as the ordering-equivalent to fences like the `smp_read_barrier_depends()` fence from linux which has been removed¹.

Sadly, it's useful. I think I've found a way to fake it, but wanted to run it by y'all. Since there's a ton of FUD around this operation (often notions that "it's not useful now that the alpha doesn't matter" — the opposite is true), I'll give some background on why it's desirable.

# Background (Why it exists, and is useful)

It exists because the DEC Alpha doesn't protect dependent reads. That is if you do:

```rust
let p = atomic_ptr.load(Relaxed);
let pointee = ptr::read(p);
```

Then the read of `p` can appear to happen "before" the `atomic_ptr.load()`². The solution in the C++ model is to use a `load(Consume)` or stronger. (Or that's the theory anyway, in practice it never worked)

Unfortunately, without consume, everybody needs this fence, since `Relaxed` (according to the C++ memory model) isn't sufficient on its own to prevent this sort of reordering (on future hardware).

Unfortunately, it's *really* just the Alpha³ that *actually needs* the fencing at all there, since everything else guarantees dependent loads will be in order. This is unfortunate, because the replacement, `load(Acquire)`/`fence(Acquire)`, is *not* free, even on machines less cursed than the Alpha. (It's free on x86 and Sparc, but I think that's it).

In particular my concern-of-the-day is 32-bit arm (v7), on which the `load(Acquire)` requires a full-blown `dmb ish` — same as if it were a `fence(SeqCst)` (https://rust.godbolt.org/z/WEvxEc). This is quite unfortunate, and is costly enough to be felt.

# Evil hack to fake it:

So, I had a thought: If the CPU guarantees dependent loads are in order, the only thing I have to worry about is the compiler, and so maybe I could get away with a `compiler_fence(Acquire)` (Admittedly this generates instructions on some platforms, but AFAICT not ARM).

FWIW even this is probably overkill, the write side needs `store(Release)` in either case, meaning it should be impossible for the compiler to load a value from a pointer from before it was written.

Anyway, the idea is this:

```rust
// architectures that are guaranteed not to need the acquire load,
// but which can still benefit from its removal.
#[cfg(any(target_arch = "arm", target_arch = "aarch64"))]
fn load_consume<T>(atomic_ptr: &AtomicPtr<T>) -> *mut T {
    let p = atomic_ptr.load(Relaxed);
    compiler_fence(Acquire);
    p
}
// everyone else
#[cfg(not(any(target_arch = "arm", target_arch = "aarch64")))]
fn load_consume<T>(atomic_ptr: &AtomicPtr<T>) -> *mut T {
    atomic_ptr.load(Acquire)
}
```

The CPU documentation guarantees that no hardware reordering can happen, and the compiler barrier should prevent issues from rustc/llvm/etc reordering. So I think this would work in practice, but is it at all sound/reasonable?

Note: I'm kind of assuming that "Make `Relaxed` guarantee that dependent access are in-order" isn't on the table, since LLVM doesn't guarantee it (AFAICT) and I suspect we aren't willing to tweak the C++ memory model that much.

---

¹ The `fence(Consume)`-alike, `smp_read_barrier_depends` was [removed](https://github.com/torvalds/linux/commit/93fab07c22930c9ac4f01212fd92913c9a812f9f) in favor of [strengthening](https://github.com/torvalds/linux/commit/8ca924aeb4f28e5bf552707e8ecbe105c4f17c7b) the kernel's memory model, which is now a lot simpler, and guarantees that dependent memory accesses will be issued in order. On the Alpha, this means they add fencing into some primitives (`load(Relaxed)`-alikes), but everywhere else it's free.

² That is, the value of `p` and `pointee` don't correspond to values which have ever matched. You could imagine this happening if the store side happened in the wrong order... But you see this even though the store to `atomic_ptr` is done with a `store(Release)`. So it seems impossible, since you need the address from the `load` in order to execute subsequent `read`. (Obviously it is possible, just hard to reason about. If you're interested, there's good documentation on what's going on under the "CACHE COHERENCY" section that the 2nd patch in footnote 1 is removing).

³ And it's not even a processor that Rust supports! LLVM removed Alpha support a long time ago (to the vague dismay of freaks like me who would (kinda) like to test their lockfree code on something *truly* weak 😛)

**Comment by RalfJung** [comment]
> This is unfortunate, because the replacement, load(Acquire)/fence(Acquire), is not free, even on machines less cursed than the Alpha. (It's free on x86 and Sparc, but I think that's it).

IMO "it's free on X" is a misleading statement here. These atomic ordering annotations are directed towards the compiler as much as they are directed towards the hardware, and so they are *never free*. They will prevent certain reorderings, and thus possibly cost performance, no matter the target.

On the actual subject of "consume" reads -- the underlying issue is that hardware memory models use a *syntactic* definition of "this values depends on that value" to make an ordering guarantee, and so far nobody demonstrated a good way to express this in the source language. There are quite a few optimizations that compilers do that break syntactic dependencies -- the most obvious one being replacing `x-x` by `0`. That's why even compilers that do not support Alpha cannot promise that dependent reads are ordered the way one might expect. So the problem has nothing to do with Alpha. (You probably know that, I just want to make sure everyone reading this is on the same page.)

Regarding compiler fences, AFAIK formally speaking they only have any effect on concurrency between a thread and a signal handler running in the same thread.

So my conclusion is what you probably expected: while this is a curious hack, unfortunately I have no idea what it would take to turn this into something "official". I also lack the knowledge to evaluate how well this hack is likely to work in practice.

**Comment by asajeffrey** [comment]
> so far nobody demonstrated a good way to express this in the source language

Plug plug our OOPSLA paper is about this. https://2020.splashcon.org/details/splash-2020-oopsla/70/Pomsets-with-Preconditions-A-Simple-Model-of-Relaxed-Memory

**Comment by comex** [comment]
As another example of compiler optimizations that can break dependencies, let's suppose you happen to write:

```rust
let p = atomic_ptr.load(Consume);
let q = /* some pointer value */;
if p == q {
    let x = *p;
}
```

The compiler would be justified in replacing `let x = *p;` with `let x = *q;`, since that line can only be reached if `p == q`.  But suddenly there is no data dependency anymore.  And a compiler memory barrier would not prevent this optimization from happening.

Of course, this kind of pattern is pretty unlikely to crop up in real code.  So is Ralf's example, where `some_array[x - x]` would be considered a dependent load according to the source language but would be optimized into `some_array[0]` by the compiler.  Why would you ever write that?  The Linux attitude is essentially: 'we won't write that, so dependent loads will stay dependent in practice'.  And they've gotten away with that, at least so far.  You could probably get away with it too.  But that's very difficult to turn into a formal guarantee, given how many different kinds of optimizations compilers either do today or may want to do in the future.

**Comment by RalfJung** [comment]
> Plug plug our OOPSLA paper is about this

Ah yes, this has been in my reading list ever since I heard about it. :) Unfortunately I didn't get to it yet...

> The compiler would be justified in replacing let x = *p; with let x = *q;, since that line can only be reached if p == q

Not really, actually, not for pointers due to provenance... but if you first cast them to an integer and then cast them back in the `if`, then it can do that.

**Comment by comex** [comment]
> Not really, actually, not for pointers due to provenance... but if you first cast them to an integer and then cast them back in the `if`, then it can do that.

Well, the compiler would still be justified in performing the *equivalent* of that replacement at the assembly level, where provenance doesn't exist anymore.  Also, LLVM [actually does](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=785c5b58414c37dfd577e624f88b5ae0) perform the equivalent of that replacement at the LLVM IR level, though I'm not sure whether that's justified or a bug. :)

**Comment by RalfJung** [comment]
That's a bug in LLVM, closely related to https://github.com/rust-lang/rust/issues/73337.

**Comment by thomcc** [comment]
> I also lack the knowledge to evaluate how well this hack is likely to work in practice.

Yeah, so not well. Or, at least, it doesn't always work, and doesn't work in many cases you'd like it to work.

It turns out that I underestimated the impact of control dependencies here, which basically makes this trick non-viable in a general way. Essentially this only works if you *only* have a data dependency, and not a control dependency. If you have a control dependency, you need stronger fencing. Its very easy to accidentally turn a data dep into a a control dep (branch on the pointers value, for example).

(It's a bit clearer now to me why even C++ compilers that support `memory_order_consume` tend to do a terrible job with it)

Tangentially, it might be worth calling out `AtomicPtr::load(Relaxed)` explicitly in something like the nomicon as warranting special care. It certainly is still valid in several cases (not all pointers are mutable, of course, and you might fence later or only in cases where you'll actually read from the pointer), but it probably deserves much more scrutiny than relaxed loads of other atomic types. (That was already true, admittedly).

Anyway, I'm closing this because my conclusion is more or less "Don't try to fake Ordering::Consume".

---

(Neither here nor there, but while I'm here...)

> IMO "it's free on X" is a misleading statement here. These atomic ordering annotations are directed towards the compiler as much as they are directed towards the hardware, and so they are never free. They will prevent certain reorderings, and thus possibly cost performance, no matter the target.

This is stritly speaking true, and I should probably be more precise about this stuff in a forum like this.

That said, in practice it's still basically free, at least in comparison to an actual fence. For a ballpark idea that might give you an idea why I say this:

A `dmb ish` (what `fence(Acquire)` lowers to on 32 bit ARM) is 20-120 instructions, depending on contention, on an (admittedly cheap) samsung phone my old employer gave me for testing a few years ago.

Conversely, a `compiler_fence(Acquire)` will often cost... literally nothing. Even if it does inhibit the compiler, and meaningfully change its output (which it frequently won't), its typically the kind of change that modern out of order CPUs see through trivially. (This is ignoring the bug where sometimes they emit real fence instructions, ofc).

That definitely isn't to say it never costs anything, or that compiler reordering is useless for out of order CPUs, but... well, a compiler_fence is not something I worry about very much.
