### ISSUE TITLE
What do we call values that do not follow AXM?

### ISSUE THREAD

**Issue by Medowhill** [rust-lang/unsafe-code-guidelines#300]
Hi all. I have questions related to the aliasing XOR mutability (AXM) discipline.

AXM is the key to the Safe Rust. It requires each value to be either aliased (via `&`) or mutable (via `&mut`), but not both at the same time. If we want to write a program that does not follow AXM, we can use Unsafe Rust. The most common way to circumvent AXM is to use interior mutability, provided by `UnsafeCell`. It allows mutation through shared references. However, it seems not every non-AXM things need interior mutability. The following example from the Stacked Borrows paper uses only raw pointers, not `UnsafeCell`, to make `x` aliased and mutable at the same time:
```rust
let mut x = 42;
let ptr1 = &mut x as *mut i32;
let ptr2 = ptr1;
unsafe { *ptr1 = 13; }
unsafe { println!("{}", *ptr2); }
```
So here come my questions:
1. Is there a term that denotes the opposite of AXM? Aliasing AND mutability would be a natural description, but I'm wondering whether there is a commonly agreed term in the Rust community.
2. If I'm not wrong, we can classify non-AXM things into those w/ interior mutability and those w/o interior mutability. For the former, we can use the term interior mutability. For the latter, what should we call them? Is there a well-established notion for the second concept?

If it's not the place to ask these questions, please let me know. Thank you!

**Comment by RalfJung** [comment]
AXM is a discipline of *reference types* in Rust. When you are not using references types, but raw pointers, AXM never comes up -- that's why the raw pointer example works. (Notice though that when you are mixing references and raw pointers, the raw pointers are not allowed to break the AXM assumptions of the references.)

Interior mutability is special because it allows shared mutable state *with references*.

> Is there a term that denotes the opposite of AXM? Aliasing AND mutability would be a natural description, but I'm wondering whether there is a commonly agreed term in the Rust community.

Not sure about the Rust community; in the PL research literature, this is often called "shared mutable state". Sadly, "shared memory" is an overloaded term: for me and my colleagues it means "memory shared between multiple threads"; for many Rustaceans it means "memory shared between multiple *processes*".

> If I'm not wrong, we can classify non-AXM things into those w/ interior mutability and those w/o interior mutability. For the former, we can use the term interior mutability. For the latter, what should we call them? Is there a well-established notion for the second concept?

I'd just use some term involving "raw pointers". The need for a specific term never came up for me; when talking about the concept I usually say things like "you can have shared mutable state with raw pointers".

**Comment by Medowhill** [comment]
Thanks a lot for your kind response!
