### ISSUE TITLE
Stack overflow when indexing with large array

### ISSUE THREAD

**Issue by LHolten** [rust-lang/unsafe-code-guidelines#382]
Here is some sample code to reproduce

```rust
use std::iter::repeat;

use dfdx::{
    tensor::{tensor, Tensor1D},
    tensor_ops::SelectTo,
};

#[test]
pub fn overflow() {
    let data = tensor([0., 1., 2.]);

    let indices: Box<[usize; 1 << 20]> = repeat(0)
        .take(1 << 20)
        .collect::<Box<[_]>>()
        .try_into()
        .unwrap();

    let res: Tensor1D<{ 1 << 20 }> = data.select(&*indices);
    drop(res)
}
```

I would expect the new `Tensor1D` to be build on the heap. But apparently it is not, causing the stack to overflow.

**Comment by bjorn3** [comment]
This is not related to unsafe code guidelines at all. In any case the issue is that dfdx inside it'd select impl creates a temporary on the stack before moving it to the heap. Rustc generally doesn't optimize the temporary away. As such dfdx should be changed to construct the tensor in place on the heap to avoid this stack overflow.

**Comment by LHolten** [comment]
Whoa, I'm so sorry! I posted this issue in the wrong repo
