### ISSUE TITLE
Return-position `noalias`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/unsafe-code-guidelines#385]
LLVM supports the `noalias` attribute in return position, and Rust uses that for functions that return `Box`. However the semantics of that are mostly unclear I think -- this has very little to do with argument-position `noalias`.

I *think* in Stacked Borrows terms it corresponds to something like: give the return value a fresh tag, and *remove all other tags from the stack*.

Questions:
- Is that the right semantics?
- Should there be some way to get return-position `noalias` without using `Box`? @gnzlbg recently [mentioned a usecase for that](https://rust-lang.zulipchat.com/#narrow/stream/136281-t-lang.2Fwg-unsafe-code-guidelines/topic/strict_provenance.20fresh.20metadata).

**Comment by RalfJung** [comment]
Specifically I think this code has UB since the returned box aliases `m`:
```rust
fn id<T>(x: Box<T>) -> Box<T> { x }

fn main() {
    let mut m = 0;
    let b = unsafe { Box::from_raw(&mut m) };
    let mut b2 = id(b);
    *b2 = 5;
    std::mem::forget(b2);
    println!("{}", m);
}
```
Miri however says this code is fine.

Cc @nikic @comex do you know the exact assumptions introduced by return-position `noalias`?

**Comment by nikic** [comment]
LangRef:

> Furthermore, the semantics of the noalias attribute on return values are stronger than the semantics of the attribute when used on function arguments. On function return values, the noalias attribute indicates that the function acts like a system memory allocation function, returning a pointer to allocated storage disjoint from the storage for any other object accessible to the caller.

So yes, that example would be UB.

**Comment by RalfJung** [comment]
So how is that supposed to work for boxes with custom allocators?

@rust-lang/wg-allocators the type `Box<T, A>` is decorated with `noalias` as a return type by Rust, which means that affected functions must return "a pointer to allocated storage disjoint from the storage for any other object accessible to the caller". Arguably this is violated by a custom allocator that hands out memory that is also accessible to the caller by other means.

In particular I see no way in LLVM to "end the scope" of that `noalias`. In particular this makes an allocator like the following unsound:
```rust
struct OnceAlloc<'a> {
    space: Cell<&'a mut [MaybeUninit<u8>]>,
}

unsafe impl<'shared, 'a: 'shared> Allocator for &'shared OnceAlloc<'a> {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, AllocError> {
        let space = self.space.replace(&mut []);

        let (ptr, len) = (space.as_mut_ptr(), space.len());

        if ptr.align_offset(layout.align()) != 0 || len < layout.size() {
            return Err(AllocError);
        }

        let slice_ptr = ptr::slice_from_raw_parts_mut(ptr as *mut u8, len);
        unsafe { Ok(NonNull::new_unchecked(slice_ptr)) }
    }

    unsafe fn deallocate(&self, _ptr: NonNull<u8>, _layout: Layout) {}
}
```

The issue is code like this
```rust
    let mut space = vec![MaybeUninit::new(0); 1];
    let once_alloc = OnceAlloc { space: Cell::new(&mut space[..]) };

    let boxed = Box::new_in([42u8; 1], &once_alloc);
    drop(boxed);
```
LLVM assumes that `boxed` does not alias `space`, causing UB when `space` gets dropped and deallocates the memory that `boxed` used to point to.

**Comment by Diggsey** [comment]
So, [previously we discussed the idea of an allocator wrapper that would apply the "allocation magic" used by LLVM to optimize allocations](https://github.com/rust-lang/wg-allocators/issues/108#issuecomment-1323233926).

Could that approach solve the same problem here? We could say that allocators such as the one you gave in your example are sound, but would be unsound if wrapped in this magic type since they don't uphold the necessary guarantees. `noalias` would only be applied by the compiler to the subset of `Box`ed types which use the magic allocator wrapper.

**Comment by RalfJung** [comment]
That would help with the immediate example, but if the semantics of return-position `noalias` are as [my PR](https://github.com/rust-lang/rust/pull/106212) defines them, only very few allocators will be able to use that magic wrapper. The LLVM requirement of being "disjoint from the storage for any other object accessible to the caller" has no time limit, and due to things like inlining "caller" recursively means basically the rest of the program. I think this is not even compatible with the concept of "nesting" allocators that we discussed previously. To make something like that possible, LLVM would have to take into account that calling `free` can move ownership of such memory back to the outside world, which poses restrictions on moving loads and stores up across `free`.

Basically return-position `noalias can only be used for `malloc` and thin wrappers around `malloc`, where deallocation removes the memory entirely from the abstract machine state. Any time that there is a "life after deallocation" inside the abstract machine, we cannot use this attribute. (LLVM better makes sure that `free` never gets inlined even with LTO, otherwise this could go wrong real badly.)

**Comment by Amanieu** [comment]
I believe these LLVM attributes were only ever designed to work in a situation where `malloc` is in a separate compilation unit (libc) and it acts as a black box to the optimizer (on both ends). This is definitely a flaw in the LLVM attribute and a better mechanism should be designed in LLVM to properly handle this situation. I know GCC and MSVC have similar attributes for return value noalias on `malloc`, so perhaps they could be involved as well?

**Comment by comex** [comment]
Indeed, putting return-position `noalias` onto all functions returning `Box` is unsound, because when LLVM assumes the return value cannot alias anything else, that includes values that existed before calling the function.  In other words, if you have
```rust
fn id(x: Box<i32>) -> Box<i32> { x }

// given a: Box<i32>
*a = 1;
let b: Box<i32> = id(a);
print(b);
```
then LLVM thinks that `a` and `b` cannot alias.  If it also knows that `id` has no side-effects, then it can reorder `*a = 1;` and `print(b);`.

The bad assumption can be demonstrated using `-aa-eval` or `-print-alias-sets`.  But I had quite a hard time actually exploiting it, because the situations where LLVM will actually reorder accesses are somewhat narrow and many of them don't apply here.  For the same reason, I'm not surprised we haven't seen reports of breakage in practice.  I did manage to exploit it though, using only safe code...
<details>
<summary>Exploitation details</summary>
My usual approach to exploiting bad noalias assumptions between A and B involves accessing A first, then B, then A again – for instance, write 100 to A, write 200 to B, then read from A, and let LLVM's GVN pass optimize the read to return 100, even though it should return 200 because A and B secretly alias.  But that isn't an option here where, before you can access B, you have to pass A through the <code>id</code> function and (because it's a <code>Box</code>) lose access to it.  Another approach is to rely on loop-invariant code motion, but that's also difficult here (at least if the goal is to use only safe code), because just putting the code in a loop would result in the compiler complaining about use-after-move of <code>a</code>.  You could replace <code>a</code> with a new value at the end of the loop, but that would make it not loop invariant.  However, I managed to get this to work by having <code>a</code> be effectively undefined on the second and further iterations… at the cost of the code that uses it being not actually reachable on those iterations, because we break out of the loop first.  This allows the optimizer to remove the loop entirely, which would prevent LICM from running, but luckily the LICM pass is executed before the pass that removes the loop.
</details>

Demo: https://rust.godbolt.org/z/6nvcqnesf

It prints `100` with optimizations enabled, but the correct value is `10`, as is printed with optimizations disabled.  Note that this only works with `-C panic=abort`.

**Comment by RalfJung** [comment]
Wait that noalias also works backwards in time on pointers before the fn was called? Wow that is not what I expected. Seems pretty broken, at leat for our usecase.

**Comment by RalfJung** [comment]
In that case I see no option than to just stop using this attribute: https://github.com/rust-lang/rust/pull/106371

**Comment by RalfJung** [comment]
Closed by https://github.com/rust-lang/rust/pull/106371
