### ISSUE TITLE
Are memory protected references that are never dereferenced in the code undefined behaviour?

### ISSUE THREAD

**Issue by timfel** [rust-lang/unsafe-code-guidelines#473]
This is motivated by how [PyO3](https://github.com/PyO3/pyo3) wraps the CPython C API for Rust. The CPython C API exposes object structures and implements OO in C via inlined structs. Take these definitions (simplified from their PyO3 definitions):

```
#[repr(C)]
pub struct PyObject {
    pub ob_refcnt: isize,
    pub ob_type: *mut PyTypeObject,
}
```

```
#[repr(C)]
pub struct PyTypeObject {
    pub ob_base: PyObject,
    pub tp_name: *const c_char,
}
```

Pointers like these are wrapped and flow through non-unsafe Rust code as 
```
#[repr(transparent)]
pub struct PyAny(UnsafeCell<PyObject>);`
```

A specific implementation of Python (GraalPy) always hands out properly allocated memory for `PyTypeObject` - so dereferencing and reading members works as expected. For plain `PyObject`, GraalPy always hands out (aligned, well-formed) pointers to protected memory, so a read would fail. However, in the Rust code we never access anything inside plain `PyObject` references - only if the reference is really to a `PyTypeObject` do we have code that reaches into it.

Everything seems to be working, but my question is: is it even undefined behavior if the memory referenced is never accessed in Rust code? All the issues and examples I can find in this repo are discussing the compiler making assumptions around code that *does* dereference. But what if we actually don't have any code that ever dereferences? Is the compiler allowed to insert spurious memory accesses even when the code never actually does access the contents of the memory?

In particular, this sentence from the book is unclear to me:

From https://doc.rust-lang.org/stable/std/cell/struct.UnsafeCell.html
> However, whenever a &UnsafeCell is constructed or dereferenced, it must still point to live memory and the compiler is allowed to insert spurious reads if it can prove that this memory has not yet been deallocated.

Does the `if` here mean the compiler is *not* allowed to insert spurious reads for PyObjects, since those are allocated and deallocated in the Python interpreter and the Rust code cannot reason about the lifetime of that memory?

**Comment by adamreichold** [comment]
Maybe to clarify one thing:

> Pointers like these are wrapped and flow through non-unsafe Rust code as

means that the safe Rust code passes shared reference `&'py PyAny` and reference-counted pointers `Py<PyAny>` around.

**Comment by CAD97** [comment]
If a read of `MaybeUninit<PyAny>` from `&PyAny` would fail, then exposing `&PyAny` is unquestionably *unsound*. The correct way to do these kinds of shenanigans is to use `extern type`.

Additionally, the current rules always consider references as dereferencable when created from a pointer and when passed as a function parameter. So while `&UnsafeCell` is allowed to start dangling within a function, it is UB if it dangles at function entry.

-----

EXPLICITLY NON-NORMATIVE: This is in a class of "probably okay, but don't count on it working forever" UB. This is because while it's UB in Rust semantics, it's not UB in the LLVM IR as we currently emit it. This is because the LLVM attribute `dereferencable(N)` lasts until function exit, and LLVM does not provide a `dereferencable_on_entry(N)` attribute yet. But the intention is that if/when it gets one to use it for `&UnsafeCell`.

**Comment by adamreichold** [comment]
> If a read of MaybeUninit<PyAny> from &PyAny would fail

Could you expand on what is meant by "fail" here. The current failure mode would be something like the process receiving SIGBUS. Elsewhere and w.r.t. `mmap`, I heard the point of view that e.g. access a memory-mapped file that has been truncated is not UB because the process dying due to SIGBUS is well-defined.

Of course, spurious reads yielding spurious SIGBUS is certainly not useful either. I am just trying to more generally understand whether and how the abstract machine considers things like address space management by the kernel.

**Comment by CAD97** [comment]
> Could you expand on what is meant by "fail" here.

I used "fail" informally there, similar to how it was used in the OP. But it certainly includes a read triggering any sort of signal, trap, or other side effect. Informally, the retag operation which is done when creating a new reference reborrow (e.g. when `&*`ing, including the implicit one for function calls) can be understood as doing a read of the referenced memory region, thus triggering UB if reads aren't side effect free.

> I heard the point of view that [some invalid pointer loads are] not UB because the process dying due to SIGBUS is well-defined.

Even in C, "a read is guaranteed to raise a fatal signal" does not make that read not UB. It's a common (and convenient) falsehood, but C is not portable assembly as specified nor as implemented by the big three compilers.

You can argue it for a volatile read, with the side effect of the read (allowed because volatile) being the termination, but that's beyond my thinking capacity atm.

> I am just trying to more generally understand whether and how the abstract machine considers things like address space management by the kernel.

It does not. Memory of the abstract machine is nonvolatile and pure; reads produce the most recently written value (ambiguous due to data race? UB) and there are no side effects. How the abstract memory (storing abstract bytes) is lowered to physical memory (storing physical bytes) is an implementation detail that needn't be reliable.

**Comment by RalfJung** [comment]
So, to summarize: currently it is *not* okay to expose a reference to memory where reading it would trap. This is similar to how it is not okay to have a reference to MMIO registers: the compiler might insert spurious reads, which would cause traps / side-effects on the MMIO hardware.

> I heard the point of view that e.g. access a memory-mapped file that has been truncated is not UB because the process dying due to SIGBUS is well-defined.

That point of view is wrong, such accesses are UB. The concrete issue here is that the compiler will consider reads as reorderable, so operations that come "after" the access in the code might actually be executed before, meaning that when the program terminates with a SIGBUS the world is in an impossible state. (Imagine first doing the access and then printing "done" to stderr; the program might end up printing "done" and then dying with SIGBUS. This is clearly a nonsense execution, so we have to declare the situation UB to explain what happens.)

**Comment by timfel** [comment]
Thanks for the clarifications!
