### ISSUE TITLE
std::slice::from_raw_parts alternative that would allow NULL pointer if len == 0 by returning an empty slice?

### ISSUE THREAD

**Issue by procedural** [rust-lang/unsafe-code-guidelines#496]
Currently, it's not allowed to pass a NULL pointer to `std::slice::from_raw_parts`, but

I have a pointer that comes from a C function that can be either:

A) A non-NULL with a len > 0
B) A NULL with a len == 0

 It would be neat if I could just write:
 
 ```rust
let values = unsafe { std::slice::from_raw_parts_or_empty(c_ptr_to_values, len) }; // Still panic if c_ptr_to_values == NULL and len > 0.
for value in values {
    // This can be skipped if values is an empty slice when c_ptr_to_values == NULL and len == 0.
    // Or values can be iterated when c_ptr_to_values != NULL and len > 0.
}
 ```

**Comment by RalfJung** [comment]
I think this is a t-libs-api issue, there are no open questions from the UCG side here.

**Comment by RalfJung** [comment]
t-libs-api has their own process that that wouldn't really make sense.

Discussing this on https://internals.rust-lang.org/ might be a good idea, otherwise the process is to file an [ACP](https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&projects=&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29). You can also always ask on Zulip. :)
