### ISSUE TITLE
Are &mut references that point to read only memory but are never written to undefined behavior

### ISSUE THREAD

**Issue by gmorenz** [rust-lang/unsafe-code-guidelines#509]
Similar to #473 but for writing instead of reading.

I'm currently writing a dynamic linker (or something very similar in nature at least), and I'm mostly wondering how careful I need to be with dropping `&mut` slices before mprotecting memory.

**Comment by chorman0773** [comment]
Creating them is certainly undefined behaviour.
Otherwise, I'd expect the mprotect operation would be equivalent to creating a new Frozen tag at the bottom of the tree and would invalidate any unrelated Active tags (and freeze unrelated Reserved tags IIRC). This isn't undefined behaviour unless any of those tags are protected (in which case it is immediate undefined behaviour) or subsequently used (in which case, it's undefined behaviour when used).

**Comment by gmorenz** [comment]
So in other words rust reserves the write to make spurious writes to memory that it can write to within the memory model?

Not surprising I guess, good to know.

**Comment by RalfJung** [comment]
> So in other words rust reserves the write to make spurious writes to memory that it can write to within the memory model?

Under Stacked Borrows, this is correct. So you should conservatively assume that this is how things work.

However, there also exists an alternative proposal for Rust's aliasing rules, dubbed Tree Borrows, where `&mut` pointing to read-only memory is entirely fine as long as you never write to it.
